# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_language_version:
  node: "16.16.0"
  python: "python3.9"
repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: "v0.3.1"
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/ambv/black
    rev: "22.6.0"
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama
        args: # arguments to configure black
          - --max-line-length=119
        # to remove when this is fixed https://github.com/klen/pylama/issues/224
        additional_dependencies:
          - pyflakes==2.4.0

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["-m=VERTICAL_HANGING_INDENT", "--combine-as", "--profile=black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-added-large-files
        exclude: data-parametrization.json.gz
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
          - "--no-ensure-ascii"

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.3.0"
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        args: [--disable-audit-and-monitor]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.9.0"
    hooks:
      - id: python-no-log-warn
      - id: python-check-mock-methods
      - id: python-no-eval

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        files: "^orange/.*"

  - repo: https://github.com/remastr/pre-commit-django-check-migrations
    rev: v0.1.0
    hooks:
      - id: check-migrations-created
        args: [--exec-command=poetry run python, --manage-path=./manage.py]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.1.0"
    hooks:
      - id: codespell
        args: ["-w"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
